/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// a program to implement a delay of 500ms using  Systick .

#include <stdint.h>
#include <stm32f401xe.h>

// GPIO definition
#define LED_Pin 5

void delay()
{
	SysTick ->LOAD = 8000000 -1;
	SysTick -> VAL = 0;
	SysTick ->CTRL =(1U << 0) | (1U << 2);

	while((SysTick ->CTRL & (1U<<16 )) == 0)

	{
		// wait
	}


	// disable clock
	SysTick->CTRL=0U;// revisit

}

int main(void)
{
	// code for blinking the led
	RCC ->AHB1ENR|= (1U<<0); // enable clock controlling SysTick
	GPIOA->MODER &= ~(3U << (2*5));
	GPIOA->MODER|=(1U << (2*5));

	while(1)
	{
		delay();

		GPIOA -> BSRR= (1U << 5);
		delay();
		GPIOA ->BSRR = (1U<< (5+16));


	}

}

