/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401xe.h>
volatile static uint32_t SysTick_Count =0;
volatile static uint32_t SysTick_LastVal =0;

static uint8_t Led_State =0;

void SysTick_Init()
{
	SysTick ->LOAD = 16000-1;
	SysTick ->VAL =0; // Needed ?
	SysTick ->CTRL= (1U<<0 ) | (1U<<2);

}

/*Function to implement a global 1ms SysTick
 *
 */
void SysTick_Update()
{


	if((SysTick ->CTRL & (1U << 16)) == 0)
	{
		// do nothing as counting has not been completed

	}
	else
	{
		SysTick_Count++;
	}


}
void GPIO_Setup()
{
	RCC ->AHB1ENR|= (1U<<0);
	GPIOA->MODER &= ~(3U << (2*5));
	GPIOA->MODER|=(1U << (2*5));
}
int main(void)
{
	//implement a non blocking delay to control LED toggle.
	// poll for the delay.  


	GPIO_Setup();
	SysTick_Init();

	while(1)
	{
		SysTick_Update();

		if(Led_State == 0)
		{

			if(SysTick_Count - SysTick_LastVal >= 500 )
			{
				GPIOA ->BSRR|= (1U << 5);
				Led_State = 1;
				SysTick_LastVal = SysTick_Count;

			}

		}
		else
		{

			if(SysTick_Count - SysTick_LastVal >= 500 )
			{
				GPIOA ->BSRR|= (1U << (5+16));
				Led_State =0;
				SysTick_LastVal = SysTick_Count;
			}

		}



	}




}
